<a href="https://colab.research.google.com/github/royn5618/Deep-Learning-Things/blob/main/NLP/HuggingFace_Transformers/GPT_2_Text_Generation_Tests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers 

In [2]:
import transformers
import torch

In [3]:
gpt_tokenizer = transformers.GPT2Tokenizer.from_pretrained('gpt2-large')

In [4]:
gpt_model = transformers.GPT2LMHeadModel.from_pretrained('gpt2-large')

In [5]:
prompt_text = 'It was raining when I started walking'

In [6]:
encoded_prompt = gpt_tokenizer.encode(prompt_text, 
                                      add_special_tokens=False, 
                                      return_tensors="pt")

encoded_prompt 

tensor([[ 1026,   373, 43079,   618,   314,  2067,  6155]])

In [7]:
## IGNORE
encoded_prompt_test = gpt_tokenizer.encode(prompt_text, 
                                      add_special_tokens=True, 
                                      return_tensors="pt")

encoded_prompt_test

tensor([[ 1026,   373, 43079,   618,   314,  2067,  6155]])

In [8]:
## IGNORE
encoded_prompt_test = gpt_tokenizer.encode(prompt_text, 
                                      add_special_tokens=True)

encoded_prompt_test

[1026, 373, 43079, 618, 314, 2067, 6155]

In [9]:
len(encoded_prompt)

1

In [10]:
max_length = 50 + len(encoded_prompt)
max_length

51

In [11]:
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=1.0,
      top_k=0,
      top_p=0.9,
      repetition_penalty=1.2,
      do_sample=True,
      num_return_sequences=1
  )

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [12]:
len(output_sequences.shape)

2

In [13]:
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
  print(type(generated_sequence)) # torch tensor type
  print(generated_sequence) # tensor of numbers/indices
  generated_sequence = generated_sequence.tolist()
  text = gpt_tokenizer.decode(generated_sequence)
  print(text)

<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,    11,   262,  2344,
         1107,   257, 36212,    13,  2893,   345,  1394,   510,   351,  3404,
          588,   428,   345,  1244,  2051,  1243,    11,   366,   339,  1297,
          502,   355,   356, 23667,   319,   262,  1218,  1621,   286,   257,
         2156,   287,   262, 24685,   626,    64,   338, 19651,  7404,   286,
         2544,  5488])
It was raining when I started walking, the wind really a nuisance. While you keep up with stuff like this you might miss things, " he told me as we descended on the second story of a house in the favela's neighboring village of Davao


In [14]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=10.0, # CHANGED
      top_k=0,
      top_p=0.9,
      do_sample=True
  ) # REMOVED repetition_penalty
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155, 21376,  7261, 34848,
         4888, 23290, 42786, 13378, 20150, 24255, 27854,  3061, 50137, 28635,
          775, 21401, 14609, 47354,  2261, 33440,  2898,  6858,  9070,  3542,
        32495, 11126, 39508, 32858, 15178,  4933, 43684, 33510, 44831,  9693,
        27008, 32736, 41273, 28582, 46253, 35129, 17949,  7546, 34831, 37532,
        49100,  5556])
It was raining when I started walking slammed tech Rebellion shared hurry Stev devoted metadatadriving Coul goal DiverCola We Assassin Zombie cellulule impatientTr Andrew Moscow closelsius dismissed Snapdragon rods ScoreUp settles combosEffectiveSH Rochester uninsured dispersemur Miscellaneous jackets anytime approvalKelly Ae creeps plus


In [15]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=2.0, # CHANGED
      top_k=0,
      top_p=0.9,
      do_sample=True
  )  # REMOVED repetition_penalty
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,   553, 48503, 22960,
        40986, 42024, 18998, 13126,  4827, 40068, 33179,  4932, 19362,  3140,
        48568,   278, 25237, 15557,   981,  9505, 14525, 29776, 33936, 50176,
        14461,  1163, 32820,  6961,  6228,  5096, 14011, 15454,   406, 26183,
          198, 37972,   318, 19280,  3833,   319,  1613,  4072,  4245,  7007,
         3840, 21742])
It was raining when I started walking," Baird resembles unab extrateralking golf labor trenches porch Guard Indianapolis ensupering ambient minorities while covering exchanges neatly arresting swath marginal officiates proposal flat insurance nonsfounder Lorman
 skeptics is blowing pressure on past emb burn requests reasons showcase


In [16]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=1.0, 
      top_k=0,
      top_p=0.9,
      do_sample=True
  )  # REMOVED repetition_penalty 
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,  3371,   262,  3770,
        17435,    13,   383,  1660,  4966,  6364,   355,   314, 12606,   625,
           13,   383,  7150,   477,  1088,   502,   925,   502,  1254,   588,
          314,   373,  6476,   281, 22007,   355,   262,  7150,  2405,  7042,
          257, 13054,  1022,   514,   290,   262,  8222,    13,  1119,   750,
          787,   502])
It was raining when I started walking towards the prison gates. The water ran slowly as I crossed over. The trees all around me made me feel like I was facing an obstacle as the trees themselves formed a barrier between us and the forest. They did make me


In [19]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=1.0,
      top_k=1, # CHANGED
      top_p=0.9,
      do_sample=True
  ) 
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,    13,   314,   373,
         6155,   287,   262,  6290,    11,   290,   314,   373,  6155,   287,
          262,  6290,    11,   290,   314,   373,  6155,   287,   262,  6290,
           11,   290,   314,   373,  6155,   287,   262,  6290,    11,   290,
          314,   373,  6155,   287,   262,  6290,    11,   290,   314,   373,
         6155,   287])
It was raining when I started walking. I was walking in the rain, and I was walking in the rain, and I was walking in the rain, and I was walking in the rain, and I was walking in the rain, and I was walking in


In [21]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=1.0,
      top_k=10, # ChANGEd
      top_p=0.9,
      do_sample=True
  )
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,   503,   290,   314,
         1422,   470,   892,   881,   546,   340,  1566,   314,   373, 19487,
          612,   290,   262,  6766,   373,   655,   523,  4950,    13,   314,
         2936,   523, 18259,   284,   307,   503,   612,   290,   284,   423,
          326,  1998,    11,   523, 14066,   284,   307,  1498,   284,   466,
          644,   314])
It was raining when I started walking out and I didn't think much about it until I was halfway there and the sky was just so beautiful. I felt so blessed to be out there and to have that experience, so grateful to be able to do what I


In [20]:
  # What happens when I do not specify num seq
  output_sequences = gpt_model.generate(
      input_ids=encoded_prompt,
      max_length=max_length + len (encoded_prompt),
      temperature=1.0,
      top_k=50, # CHANGED
      top_p=0.7, # CHANGED
      repetition_penalty=1.2,
      do_sample=True
  )
for generated_sequence_idx, generated_sequence in enumerate(output_sequences):
    print(type(generated_sequence)) # torch tensor type
    print(generated_sequence) # tensor of numbers/indices
    generated_sequence = generated_sequence.tolist()
    text = gpt_tokenizer.decode(generated_sequence)
    print(text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


<class 'torch.Tensor'>
tensor([ 1026,   373, 43079,   618,   314,  2067,  6155,    11,   290,   340,
         1392,  4785,   355,   262,  1110,  1816,   319,    13,   383,  6290,
          373, 23147,   866,   422,  2029,   523,   314,   714,  3285,   257,
         1256,   286, 14788,  2406,   422,  2354,   616,  2156,   553,   531,
          509,  1000,   268,   337,   397,   622,    74,    13,   198,   198,
            1,  1858])
It was raining when I started walking, and it got worse as the day went on. The rain was pouring down from above so I could hear a lot of screaming coming from outside my house," said Kaleen Mabruk.

"There
